1)Filter the data to include only weekdays (Monday to Friday) and plot a line graph showing the pedestrian counts for each day of the week.

In [15]:
import pandas as pd
import matplotlib.pyplot as plt

# Read the dataset
url = "https://data.cityofnewyork.us/api/views/6fi9-q3ta/rows.csv?accessType=DOWNLOAD"
pd.read_csv(url)
# Convert 'Date' column to datetime format
df['hour_beginning'] = pd.to_datetime(df['hour_beginning'])

# Filter data to include only weekdays
weekdays = df[df['hour_beginning'].dt.dayofweek < 5]

# Group by day of the week and sum pedestrian counts
pedestrian_counts = weekdays.groupby(weekdays['hour_beginning'].dt.day_name()).sum()

# Plot line graph
plt.plot(pedestrian_counts)
plt.title('Pedestrian Counts for Each Day of the Week')
plt.xlabel('Day of the Week')
plt.ylabel('Pedestrian Count')
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

,hour_beginning,location,Pedestrians,Towards Manhattan,Towards Brooklyn,weather_summary,temperature,precipitation,lat,long,events,Location1
0,04/30/2019 12:00:00 AM,Brooklyn Bridge,3,3,0,NaN,NaN,NaN,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)"
1,12/31/2019 10:00:00 PM,Brooklyn Bridge,10,9,1,cloudy,42.0,0.0005,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)"
2,12/31/2019 11:00:00 PM,Brooklyn Bridge,2,0,2,cloudy,42.0,0.0004,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)"
3,12/31/2019 09:00:00 PM,Brooklyn Bridge,12,0,12,cloudy,42.0,0.0036,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)"
4,04/01/2019 03:00:00 AM,Brooklyn Bridge,1,0,1,clear-night,36.0,0.0000,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)"
...,...,...,...,...,...,...,...,...,...,...,...,...
16052,06/22/2018 04:00:00 AM,Brooklyn Bridge,7,4,3,partly-cloudy-night,67.0,0.0000,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)"
16053,07/19/2018 06:00:00 AM,Brooklyn Bridge,192,89,103,clear-day,65.0,0.0000,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)"
16054,06/16/2018 04:00:00 PM,Brooklyn Bridge,2623,1161,1462,clear-day,82.0,0.0000,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)"
16055,07/24/2018 06:00:00 PM,Brooklyn Bridge,2016,1069,947,partly-cloudy-day,80.0,0.0000,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)"
16056,07/23/2018 12:00:00 AM,Brooklyn Bridge,57,20,37,cloudy,75.0,0.0103,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)"

2.Track pedestrian counts on the Brooklyn Bridge for the year 2019 and analyze how different weather conditions influence pedestrian activity in that year:

In [28]:
import pandas as pd

# Read the dataset
url = "https://data.cityofnewyork.us/api/views/6fi9-q3ta/rows.csv?accessType=DOWNLOAD"
df = pd.read_csv(url)

# Convert 'hour_beginning' column to datetime format
df['hour_beginning'] = pd.to_datetime(df['hour_beginning'])

# Filter data for the year 2019 and Brooklyn Bridge location
brooklyn_bridge_2019 = df[(df['hour_beginning'].dt.year == 2019) & (df['location'] == 'Brooklyn Bridge')]

# Analyze pedestrian counts by weather summary
pedestrian_counts_by_weather = brooklyn_bridge_2019.groupby('weather_summary')['Pedestrians'].sum()

# Print pedestrian counts by weather summary
print("Pedestrian counts by weather summary:")
print(pedestrian_counts_by_weather)

# Analyze the correlation between weather summary and pedestrian counts
correlation_matrix = brooklyn_bridge_2019[['Pedestrians', 'weather_summary']].corr()

# Print correlation matrix
print("\nCorrelation Matrix:")
print(correlation_matrix)

Pedestrian counts by weather summary:
weather_summary
clear-day              1953025
clear-night              61815
cloudy                  984867
fog                       4673
partly-cloudy-day      2790868
partly-cloudy-night      63794
rain                    139502
sleet                     1426
snow                      8460
wind                      2716
Name: Pedestrians, dtype: int64

Correlation Matrix:
             Pedestrians
Pedestrians          1.0

<ipython-input-28-f37daa2882ad>:21: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation_matrix = brooklyn_bridge_2019[['Pedestrians', 'weather_summary']].corr()

3. Implement a custom function to categorize time of day into morning, afternoon, evening, and night:

In [30]:
import pandas as pd

# Read the dataset
url = "https://data.cityofnewyork.us/api/views/6fi9-q3ta/rows.csv?accessType=DOWNLOAD"
df = pd.read_csv(url)

# Convert 'hour_beginning' column to datetime format
df['hour_beginning'] = pd.to_datetime(df['hour_beginning'])

# Define a function to categorize time of day
def categorize_time_of_day(hour):
    if 5 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 20:
        return 'Evening'
    else:
        return 'Night'

# Apply the function to create a new column for time of day categories
df['Time of Day'] = df['hour_beginning'].dt.hour.apply(categorize_time_of_day)

# Print the DataFrame to verify the new column
print(df[['hour_beginning', 'Time of Day']])

           hour_beginning Time of Day
0     2019-04-30 00:00:00       Night
1     2019-12-31 22:00:00       Night
2     2019-12-31 23:00:00       Night
3     2019-12-31 21:00:00       Night
4     2019-04-01 03:00:00       Night
...                   ...         ...
16052 2018-06-22 04:00:00       Night
16053 2018-07-19 06:00:00     Morning
16054 2018-06-16 16:00:00   Afternoon
16055 2018-07-24 18:00:00     Evening
16056 2018-07-23 00:00:00       Night

[16057 rows x 2 columns]